export const GET_CATEGORY = "CATEGORY/GET_CATEGORY";
export const GET_CATEGORY_SUCCESS = "CATEGORY/GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "CATEGORY/GET_CATEGORY_ERROR";

export const GET_FILTER_CATEGORY = "CATEGORY/GET_FILTER_CATEGORY";
export const GET_FILTER_CATEGORY_SUCCESS = "CATEGORY/GET_FILTER_CATEGORY_SUCCESS";
export const GET_FILTER_CATEGORY_ERROR = "CATEGORY/GET_FILTER_CATEGORY_ERROR";