export const GET_PRODUCTS = "PRODUCT/GET_PRODUCT";
export const GET_PRODUCTS_SUCCESS = "PRODUCT/GET_PRODUCT_SUCCESS";
export const GET_PRODUCTS_ERROR = "PRODUCT/GET_PRODUCT_ERROR";

export const GET_SELLING_PRODUCTS = "PRODUCT/GET_SELLING_PRODUCTS";
export const GET_SELLING_PRODUCTS_SUCCESS = "PRODUCT/GET_SELLING_PRODUCTS_SUCCESS";
export const GET_SELLING_PRODUCTS_ERROR = "PRODUCT/GET_SELLING_PRODUCTS_ERROR";

export const GET_HOT_PRODUCTS = "PRODUCT/GET_HOT_PRODUCTS";
export const GET_HOT_PRODUCTS_SUCCESS = "PRODUCT/GET_HOT_PRODUCTS_SUCCESS";
export const GET_HOT_PRODUCTS_ERROR = "PRODUCT/GET_HOT_PRODUCTS_ERROR";